/*
 * This source file was generated by the Gradle 'init' task
 */
package story_game;

import story_game.gui.window.MainMenuWindow;
import story_game.save_mechanics.SaveFile;
import story_game.save_mechanics.SaveHandler;

class AppTest {
    public static void main(String[] args) {
        SaveFile save = new SaveFile();
        SaveHandler.saveFile(save, "save2");
        SaveHandler.saveFile(save, "save3");
        System.out.println(SaveHandler.loadGame("save1"));
        MainMenuWindow.launch(MainMenuWindow.class, args);
    }
}
