/*
 * This source file was generated by the Gradle 'init' task
 */
package story_game;

import story_game.gui.MainMenu;
import story_game.save_mechanics.SaveFile;
import story_game.save_mechanics.SaveHandler;

class AppTest {
    public static void main(String[] args) {
        SaveFile save = new SaveFile();
        SaveHandler.saveGame(save,"save1");
        System.out.println(SaveHandler.loadGame("save1"));
        MainMenu.launch(MainMenu.class, args);
    }
}
